### ISSUE TITLE
[Bug]: No custom GUI for Alchemy Table

### ISSUE THREAD

**Issue by SkyeMors** [Digitalroot-Valheim/GraveofBears-PotionsPlus#3]
### How are you playing the game?

Single Player - No Server

### What happened?

I expected the GUI shown on the mod's page to show up when interacting with the alchemy table or brewing cauldron.
Not sure if incompatibility or outright bug, or feature that's not added yet.

### To Reproduce

1. Go to Zoe's Alchemy Table
2. Open table
3. See error (lack of custom GUI)

### Screenshots

![image](https://user-images.githubusercontent.com/39830646/151682741-998dde3e-bde7-4083-8cf6-8558f3ab4be6.png)
![image](https://user-images.githubusercontent.com/39830646/151682904-30115a1d-24bf-4a07-9321-ba346274dc6e.png)
![image](https://user-images.githubusercontent.com/39830646/151682917-87264e8c-f47e-4934-b902-0c5b6a2b7b25.png)

### Log File

[LogOutput.log](https://github.com/Digitalroot-Valheim/GraveofBears-PotionsPlus/files/7965108/LogOutput.log)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
That is from the Project Auga mod https://www.nexusmods.com/valheim/mods/1413
